### ISSUE TITLE
Public roadmap

### ISSUE THREAD

**Issue by TrySound** [draft-js-plugins/draft-js-plugins#1313]
- [x] drop union-class-names (replaced with clsx)
- [x] drop decorate-component-with-props (replaced with locally defined function component)
- [x] drop lodash.* packages in favour of lodash/* packages
- [x] upgrade to draft-js v0.11 + fix incompatibility because of new arguments
- [ ] migrate plugins to plugin instance as first argument to prevent breaking changes like in previous case
- [x] upgrade to babel v7 (temporary migrated to babel-plugin-css-modules)
- [ ] upgrade to react v16 and drop deprecated lifecycle hooks
- [x] replace babel-plugin-webpack-loaders with linaria for generating css
- [ ] make draft-js-plugin-mentions controlled (open, onOpen, onClose) and drop tracking of suggestions changes
- [x] upgrade storybook (currently broken after babel upgrade)
- [ ] add esm support to all modules (via module field in package.json)

**Comment by lucasreppewelander** [comment]
What do you believe would be the timeframe on react 16?

I added this plugins with the mentions plugin and the plugin editor, it works, kind of.
It throws these messages everywhere I click or type anything:

```
Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
```

and I get the error inside `PluginEditor` says the warning..

**Comment by TrySound** [comment]
@lucasreppewelander The problem is on your side. Try this
```
onChange={(editorState, instance) => setEditorState(editorState)}
```

**Comment by TrySound** [comment]
Warnings about deprecated lifecycles will be fixed in upcoming release.

**Comment by tarjei** [comment]
Any idea how much is left before the next release?

**Comment by sibelius** [comment]
I'm gonna close this now

reopen specific issues
